# Generated by Django 4.1 on 2022-09-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_id', models.IntegerField(verbose_name='internal code')),
                ('cur_parent_id', models.IntegerField(verbose_name='reference code')),
                ('numeric_code', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=256)),
                ('name_bel', models.CharField(max_length=256)),
                ('name_eng', models.CharField(max_length=256)),
                ('quot_name', models.CharField(max_length=256)),
                ('quot_name_bel', models.CharField(max_length=256)),
                ('quot_name_eng', models.CharField(max_length=256)),
                ('name_multi', models.CharField(max_length=256)),
                ('name_multi_bel', models.CharField(max_length=256)),
                ('name_multi_eng', models.CharField(max_length=256)),
                ('scale', models.IntegerField(verbose_name='exchange units')),
                ('periodicity', models.IntegerField(verbose_name='periodicity(0 – daily, 1 – monthly)')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('official', models.DecimalField(decimal_places=4, max_digits=13)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.currency')),
            ],
        ),
    ]
